// Catálogo audiovisual Paleomagina — rutas, playlists y piezas (ES/EN)
const audiovisualCatalog = {
  es: {
    routes: [
      { id: "geo", title: "Geología y paisaje", text: "Tiempo profundo, placas tectónicas, rocas y formación del relieve de Sierra Mágina." },
      { id: "paleo", title: "Fósiles y vida antigua", text: "Mares antiguos, fósiles, fauna cuaternaria y reconstrucción de ecosistemas pasados." },
      { id: "human", title: "Evolución humana", text: "Neandertales, arte, tecnología lítica y cambios en las formas de vida." },
      { id: "arch", title: "Arqueología y método", text: "Excavación, datación, evidencias materiales y construcción del conocimiento científico." },
      { id: "museum", title: "Museo y visita", text: "Cómo los audiovisuales complementan ámbitos, línea temporal, glosario y terraza final." },
    ],
    playlists: [
      { id: "before", title: "Antes de la visita", text: "Vídeos breves para situar el territorio, el tiempo geológico y las grandes preguntas del recorrido." },
      { id: "during", title: "Durante el recorrido", text: "Piezas que enlazan con ámbitos concretos mientras avanzas por la exposición." },
      { id: "after", title: "Después de la visita", text: "Profundiza metodología, paisaje y memoria territorial una vez completado el circuito." },
    ],
    levels: { general: "Público general", school: "Centros educativos", all: "Todos los niveles" },
    items: [
      {
        id: "yt-placas",
        youtubeId: "bffze7j_wWE",
        theme: "geo",
        playlists: ["before"],
        scope: "A2",
        level: "general",
        icon: "🌐",
        title: "Bordes de placa en 10 minutos",
        summary: "Resumen sobre bordes de placa, terremotos y volcanes.",
        learn: ["Relaciona procesos tectónicos con relieve y riesgos geológicos.", "Prepara la lectura de geología y orografía en el recorrido."],
        glossary: ["Falla", "Plegamiento", "Geología"],
        transcript: "El vídeo explica qué son los bordes de placa, cómo se desplazan las masas litosféricas y por qué aparecen terremotos y volcanes. Es una introducción útil para entender cómo se forman cordilleras como la Bética y el paisaje actual de Sierra Mágina.",
        teacher: "¿Qué relación hay entre placas tectónicas y el relieve que vemos hoy? · Dibuja un esquema simple de colisión entre placas.",
        duration: "10 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "yt-iberia-geo",
        youtubeId: "OCPjD_dzcls",
        theme: "geo",
        playlists: ["before", "during"],
        scope: "A2",
        level: "school",
        icon: "🧭",
        title: "Evolución geológica de la Península Ibérica",
        summary: "Guía sobre la historia geológica de la península.",
        learn: ["Sitúa Sierra Mágina dentro de la evolución geológica de Iberia.", "Conecta mares antiguos, sedimentos y levantamientos tectónicos."],
        glossary: ["Mesozoico", "Sedimento", "Orografía"],
        transcript: "Recorre las grandes etapas que transformaron la península: antiguos océanos, sedimentación, orogenias y modelado del relieve. Ayuda a comprender por qué en zonas interiores montañosas aún encontramos fósiles marinos.",
        teacher: "¿Qué etapas geológicas reconoces en el vídeo? · ¿Por qué Iberia conserva evidencias de antiguos mares?",
        duration: "15 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "yt-tierra",
        youtubeId: "5i9zPNzfdbU",
        theme: "geo",
        playlists: ["before"],
        scope: "A1",
        level: "general",
        icon: "🌍",
        title: "Evolución de la Tierra",
        summary: "Origen del planeta y grandes cambios a lo largo del tiempo.",
        learn: ["Introduce la escala del tiempo geológico.", "Prepara la línea temporal interactiva del museo."],
        glossary: ["Geología", "Cenozoico", "Línea temporal"],
        transcript: "Presenta el origen de la Tierra y los procesos que la han transformado: formación de la atmósfera, aparición de océanos, cambios climáticos y evolución de la vida. Es una puerta de entrada al relato temporal del centro.",
        teacher: "Ordena cinco hitos del vídeo en una línea temporal dibujada. · ¿Qué escala temporal te resulta más difícil de imaginar?",
        duration: "12 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "yt-estructura",
        youtubeId: "Mx4RpaJ9OOA",
        theme: "geo",
        playlists: ["before"],
        scope: "A2",
        level: "school",
        icon: "🧪",
        title: "Estructura y composición de la Tierra",
        summary: "Capas internas del planeta y sus materiales.",
        learn: ["Diferencia corteza, manto y núcleo.", "Relaciona procesos internos con fenómenos en superficie."],
        glossary: ["Geología", "Sedimento", "Falla"],
        transcript: "Describe las capas que forman el planeta y cómo influyen en volcanismo, terremotos y formación de rocas. Refuerza la idea de que el territorio visible es solo la parte superior de un sistema mucho más complejo.",
        teacher: "Etiqueta un diagrama de capas terrestres. · ¿Qué capa condiciona directamente lo que excavamos o estudiamos en superficie?",
        duration: "11 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "yt-escala",
        youtubeId: "ptO0m3BjghQ",
        theme: "geo",
        playlists: ["before", "during"],
        scope: "A1",
        level: "general",
        icon: "⏳",
        title: "Escala de tiempo geológico",
        summary: "Eras y periodos que ordenan la historia de la Tierra.",
        learn: ["Entrena la lectura de eras y periodos.", "Facilita la comprensión de la secuencia expositiva."],
        glossary: ["Mesozoico", "Cuaternario", "Cenozoico"],
        transcript: "Explica cómo los geólogos dividen el tiempo en eras y periodos, y qué eventos marcan cada tramo. Es clave para no perderse entre millones de años y cambios humanos recientes.",
        teacher: "Construye una escala con al menos cuatro divisiones y un ejemplo de cada una.",
        duration: "9 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "yt-historia",
        youtubeId: "UEx5hCcxO-Y",
        theme: "geo",
        playlists: ["before"],
        scope: "A0",
        level: "general",
        icon: "📚",
        title: "Historia de la Tierra",
        summary: "Hitos del desarrollo geológico del planeta.",
        learn: ["Resume los grandes cambios del planeta.", "Conecta geología con aparición y evolución de la vida."],
        glossary: ["Fósil", "Paleontología", "Geología"],
        transcript: "Recorre acontecimientos como la formación de la Luna, la aparición de la vida, la diversificación de organismos y las grandes extinciones. Sirve como mapa general antes de entrar en los ámbitos del museo.",
        teacher: "Elige tres hitos y explícalos con tus propias palabras.",
        duration: "14 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "yt-rocas",
        youtubeId: "3Vaj7YNepik",
        theme: "geo",
        playlists: ["during"],
        scope: "A2",
        level: "school",
        icon: "🪨",
        title: "Tipos de rocas",
        summary: "Rocas ígneas, sedimentarias y metamórficas.",
        learn: ["Identifica tipos de roca en vitrinas y paneles.", "Relaciona rocas con procesos y fósiles."],
        glossary: ["Caliza", "Sedimento", "Dolomía"],
        transcript: "Clasifica las rocas según su origen y proceso de formación. En Paleomagina esta base ayuda a leer calizas, margas y dolomías presentes en el territorio de Sierra Mágina.",
        teacher: "Busca ejemplos de cada tipo de roca en fotografías del museo o del paisaje.",
        duration: "8 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "yt-placas2",
        youtubeId: "Vx6ESMK4CCk",
        theme: "geo",
        playlists: ["before"],
        scope: "A2",
        level: "general",
        icon: "🌍",
        title: "Placas tectónicas",
        summary: "Origen de océanos y movimiento de placas.",
        learn: ["Comprende deriva continental y formación de cuencas.", "Enlaza con el antiguo mar de Tetis."],
        glossary: ["Tetis", "Falla", "Levantamiento tectónico"],
        transcript: "Explica la teoría de placas tectónicas con ejemplos de dorsales, subducción y colisión. Permite entender cómo un fondo marino puede acabar convertido en montaña.",
        teacher: "¿Qué proceso tectónico explica que haya fósiles marinos en la sierra?",
        duration: "7 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "yt-iberia2",
        youtubeId: "Mpj8__oHbaw",
        theme: "geo",
        playlists: ["during"],
        scope: "A2",
        level: "general",
        icon: "🧭",
        title: "Evolución geológica de Iberia",
        summary: "Cambios geológicos recientes de la península.",
        learn: ["Refuerza la lectura del relieve peninsular.", "Prepara la terraza final y el mapa interactivo."],
        glossary: ["Sierra Mágina", "Orografía", "Erosión"],
        transcript: "Sintetiza procesos que modelaron la península en los últimos millones de años. Conecta la escala ibérica con la lectura local del paisaje desde la terraza del centro.",
        teacher: "Compara el relieve de Sierra Mágina con el mapa general de Iberia.",
        duration: "6 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "pm-tetis",
        theme: "paleo",
        playlists: ["during"],
        scope: "A1",
        level: "general",
        icon: "🌊",
        title: "Del mar de Tetis a Sierra Mágina",
        summary: "Serie Paleomagina · pieza sobre el origen marino del territorio.",
        learn: ["Introduce el ámbito del mar de Tetis.", "Explica fósiles marinos en un entorno montañoso."],
        glossary: ["Tetis", "Ammonite", "Fósil"],
        transcript: "Recorrido narrado por el ámbito A1: de un océano tropical a un territorio interior con fósiles marinos conservados en la roca. Pensado para verse antes o después de la vitrina de ammonites.",
        teacher: "¿Qué evidencias del vídeo reconocerías en sala? · Dibuja la secuencia mar → sedimento → montaña.",
        duration: "8 min",
        planned: true,
        source: "paleomagina",
        ambitoLink: "ambitos.html",
      },
      {
        id: "pm-fosiles",
        theme: "geo",
        playlists: ["during"],
        scope: "A2",
        level: "school",
        icon: "⛰️",
        title: "Cómo una montaña conserva fósiles marinos",
        summary: "Serie Paleomagina · geología y relieve explicados con evidencias.",
        learn: ["Une geología, sedimentos y paisaje kárstico.", "Prepara la lectura del mapa y la terraza."],
        glossary: ["Caliza", "Kárstico", "Estratigrafía"],
        transcript: "Explica cómo capas sedimentarias marinas se pliegan, se elevan y se erosionan hasta formar el relieve actual. La pieza enlaza paneles de geología con la vista exterior.",
        teacher: "Identifica en el vídeo tres procesos: sedimentación, elevación y erosión.",
        duration: "9 min",
        planned: true,
        source: "paleomagina",
        ambitoLink: "ambitos.html",
      },
      {
        id: "pm-neanderthal",
        theme: "human",
        playlists: ["during"],
        scope: "A4",
        level: "general",
        icon: "🔥",
        title: "Neandertales en el territorio",
        summary: "Serie Paleomagina · vida, frío y evidencias humanas.",
        learn: ["Contextualiza el ámbito del mundo neandertal.", "Relaciona tecnología lítica y adaptación al frío."],
        glossary: ["Homo neanderthalensis", "Paleolítico", "Industria lítica"],
        transcript: "Presenta cómo vivieron los neandertales en entornos fríos, qué herramientas fabricaron y qué restos se documentan en el territorio. Complementa la antesala y el ámbito A4.",
        teacher: "Lista tres adaptaciones al frío mencionadas en el vídeo.",
        duration: "10 min",
        planned: true,
        source: "paleomagina",
        ambitoLink: "ambitos.html",
      },
      {
        id: "pm-excavacion",
        theme: "arch",
        playlists: ["after"],
        scope: "A8",
        level: "school",
        icon: "🔬",
        title: "La ciencia detrás de una excavación",
        summary: "Serie Paleomagina · método, registro y laboratorio.",
        learn: ["Muestra cómo se produce conocimiento arqueológico.", "Enlaza con ciencia y ciudadanía."],
        glossary: ["Excavación arqueológica", "Carbono 14", "Método científico"],
        transcript: "Describe fases de una excavación: prospección, cuadrícula, registro, laboratorio y publicación. Humaniza el trabajo científico que aparece en el ámbito A8.",
        teacher: "Ordena las fases del vídeo y explica por qué el contexto es tan importante.",
        duration: "11 min",
        planned: true,
        source: "paleomagina",
        ambitoLink: "ambitos.html",
      },
      {
        id: "pm-terraza",
        theme: "museum",
        playlists: ["after"],
        scope: "ATZ",
        level: "general",
        icon: "🌄",
        title: "La terraza final: leer el paisaje",
        summary: "Serie Paleomagina · cierre entre sala y horizonte real.",
        learn: ["Cierra el recorrido conectando interior y paisaje.", "Invita a continuar la visita fuera del edificio."],
        glossary: ["Terraza final", "Sierra Mágina", "Interpretación del patrimonio"],
        transcript: "Relaciona lo visto en vitrinas y paneles con laderas, crestas y valles visibles desde la terraza. Es el cierre audiovisual del relato museográfico.",
        teacher: "Desde la terraza, señala tres elementos del paisaje mencionados en el vídeo.",
        duration: "7 min",
        planned: true,
        source: "paleomagina",
        ambitoLink: "ambitos.html",
      },
    ],
  },
  en: {
    routes: [
      { id: "geo", title: "Geology and landscape", text: "Deep time, plate tectonics, rocks, and how Sierra Mágina's relief was formed." },
      { id: "paleo", title: "Fossils and ancient life", text: "Ancient seas, fossils, Quaternary fauna, and reconstruction of past ecosystems." },
      { id: "human", title: "Human evolution", text: "Neanderthals, art, stone technology, and changes in ways of life." },
      { id: "arch", title: "Archaeology and method", text: "Excavation, dating, material evidence, and how scientific knowledge is built." },
      { id: "museum", title: "Museum and visit", text: "How audiovisuals complement scopes, timeline, glossary, and the final terrace." },
    ],
    playlists: [
      { id: "before", title: "Before your visit", text: "Short videos to place the territory, geological time, and the route's big questions." },
      { id: "during", title: "During the route", text: "Pieces linked to specific scopes as you move through the exhibition." },
      { id: "after", title: "After your visit", text: "Go deeper into method, landscape, and territorial memory once the circuit is complete." },
    ],
    levels: { general: "General audience", school: "School groups", all: "All levels" },
    items: [
      {
        id: "yt-placas",
        youtubeId: "bffze7j_wWE",
        theme: "geo",
        playlists: ["before"],
        scope: "A2",
        level: "general",
        icon: "🌐",
        title: "Plate boundaries in 10 minutes",
        summary: "Overview of plate boundaries, earthquakes, and volcanoes.",
        learn: ["Links tectonic processes to relief and geological hazards.", "Prepares the geology and relief section of the route."],
        glossary: ["Fault", "Folding", "Geology"],
        transcript: "The video explains what plate boundaries are, how lithospheric plates move, and why earthquakes and volcanoes occur. It is a useful introduction to understanding ranges such as the Betic chain and today's landscape of Sierra Mágina.",
        teacher: "What is the link between plate tectonics and today's relief? · Draw a simple diagram of plate collision.",
        duration: "10 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "yt-iberia-geo",
        youtubeId: "OCPjD_dzcls",
        theme: "geo",
        playlists: ["before", "during"],
        scope: "A2",
        level: "school",
        icon: "🧭",
        title: "Geological evolution of the Iberian Peninsula",
        summary: "Guide to the peninsula's geological history.",
        learn: ["Places Sierra Mágina within Iberia's geological evolution.", "Connects ancient seas, sediments, and tectonic uplift."],
        glossary: ["Mesozoic", "Sediment", "Orography"],
        transcript: "Covers the main stages that transformed the peninsula: ancient oceans, sedimentation, orogenies, and relief shaping. Helps explain why marine fossils still appear in inland mountain areas.",
        teacher: "Which geological stages do you recognise in the video? · Why does Iberia preserve evidence of ancient seas?",
        duration: "15 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "yt-tierra",
        youtubeId: "5i9zPNzfdbU",
        theme: "geo",
        playlists: ["before"],
        scope: "A1",
        level: "general",
        icon: "🌍",
        title: "Evolution of the Earth",
        summary: "Origin of the planet and major changes over time.",
        learn: ["Introduces the geological time scale.", "Prepares the museum's interactive timeline."],
        glossary: ["Geology", "Cenozoic", "Timeline"],
        transcript: "Presents the origin of the Earth and processes that transformed it: atmosphere, oceans, climate change, and the evolution of life. A gateway to the centre's temporal narrative.",
        teacher: "Order five milestones from the video on a drawn timeline. · Which time scale is hardest to imagine?",
        duration: "12 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "yt-estructura",
        youtubeId: "Mx4RpaJ9OOA",
        theme: "geo",
        playlists: ["before"],
        scope: "A2",
        level: "school",
        icon: "🧪",
        title: "Structure and composition of the Earth",
        summary: "Internal layers of the planet and their materials.",
        learn: ["Distinguishes crust, mantle, and core.", "Links internal processes to surface phenomena."],
        glossary: ["Geology", "Sediment", "Fault"],
        transcript: "Describes the layers that make up the planet and how they influence volcanism, earthquakes, and rock formation. Reinforces that visible territory is only the top of a much larger system.",
        teacher: "Label a diagram of Earth's layers. · Which layer directly conditions what we study at the surface?",
        duration: "11 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "yt-escala",
        youtubeId: "ptO0m3BjghQ",
        theme: "geo",
        playlists: ["before", "during"],
        scope: "A1",
        level: "general",
        icon: "⏳",
        title: "Geological time scale",
        summary: "Eras and periods that order Earth's history.",
        learn: ["Practises reading eras and periods.", "Supports understanding of the exhibition sequence."],
        glossary: ["Mesozoic", "Quaternary", "Cenozoic"],
        transcript: "Explains how geologists divide time into eras and periods and what events mark each span. Key for moving between millions of years and recent human change.",
        teacher: "Build a scale with at least four divisions and one example for each.",
        duration: "9 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "yt-historia",
        youtubeId: "UEx5hCcxO-Y",
        theme: "geo",
        playlists: ["before"],
        scope: "A0",
        level: "general",
        icon: "📚",
        title: "History of the Earth",
        summary: "Milestones in the planet's geological development.",
        learn: ["Summarises major planetary changes.", "Connects geology with the appearance and evolution of life."],
        glossary: ["Fossil", "Paleontology", "Geology"],
        transcript: "Covers events such as the Moon's formation, the appearance of life, diversification of organisms, and major extinctions. Works as a general map before entering the museum scopes.",
        teacher: "Choose three milestones and explain them in your own words.",
        duration: "14 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "yt-rocas",
        youtubeId: "3Vaj7YNepik",
        theme: "geo",
        playlists: ["during"],
        scope: "A2",
        level: "school",
        icon: "🪨",
        title: "Types of rocks",
        summary: "Igneous, sedimentary, and metamorphic rocks.",
        learn: ["Identifies rock types in cases and panels.", "Links rocks to processes and fossils."],
        glossary: ["Limestone", "Sediment", "Dolomite"],
        transcript: "Classifies rocks by origin and formation process. At Paleomagina this foundation helps read limestone, marl, and dolomite in the Sierra Mágina territory.",
        teacher: "Find examples of each rock type in museum photos or the landscape.",
        duration: "8 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "yt-placas2",
        youtubeId: "Vx6ESMK4CCk",
        theme: "geo",
        playlists: ["before"],
        scope: "A2",
        level: "general",
        icon: "🌍",
        title: "Plate tectonics",
        summary: "Origin of oceans and plate movement.",
        learn: ["Understands continental drift and basin formation.", "Links to the ancient Tethys Sea."],
        glossary: ["Tethys", "Fault", "Tectonic uplift"],
        transcript: "Explains plate tectonics with examples of ridges, subduction, and collision. Shows how a seabed can end up as a mountain range.",
        teacher: "Which tectonic process explains marine fossils in the mountain range?",
        duration: "7 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "yt-iberia2",
        youtubeId: "Mpj8__oHbaw",
        theme: "geo",
        playlists: ["during"],
        scope: "A2",
        level: "general",
        icon: "🧭",
        title: "Geological evolution of Iberia",
        summary: "Recent geological changes in the peninsula.",
        learn: ["Reinforces reading of peninsular relief.", "Prepares the final terrace and interactive map."],
        glossary: ["Sierra Mágina", "Orography", "Erosion"],
        transcript: "Summarises processes that shaped the peninsula in recent millions of years. Connects the Iberian scale with local landscape reading from the centre's terrace.",
        teacher: "Compare Sierra Mágina's relief with the general map of Iberia.",
        duration: "6 min",
        subtitle: true,
        source: "external",
      },
      {
        id: "pm-tetis",
        theme: "paleo",
        playlists: ["during"],
        scope: "A1",
        level: "general",
        icon: "🌊",
        title: "From the Tethys Sea to Sierra Mágina",
        summary: "Paleomagina series · piece on the territory's marine origin.",
        learn: ["Introduces the Tethys Sea scope.", "Explains marine fossils in a mountain setting."],
        glossary: ["Tethys", "Ammonite", "Fossil"],
        transcript: "Narrated route through scope A1: from a tropical ocean to an inland territory with marine fossils preserved in rock. Designed to watch before or after the ammonite display.",
        teacher: "Which evidence from the video would you recognise in the gallery? · Draw the sequence sea → sediment → mountain.",
        duration: "8 min",
        planned: true,
        source: "paleomagina",
        ambitoLink: "ambitos.html",
      },
      {
        id: "pm-fosiles",
        theme: "geo",
        playlists: ["during"],
        scope: "A2",
        level: "school",
        icon: "⛰️",
        title: "How a mountain keeps marine fossils",
        summary: "Paleomagina series · geology and relief through evidence.",
        learn: ["Links geology, sediments, and karst landscape.", "Prepares map reading and the terrace."],
        glossary: ["Limestone", "Karst", "Stratigraphy"],
        transcript: "Explains how marine sedimentary layers fold, rise, and erode to form today's relief. Links geology panels with the outdoor view.",
        teacher: "Identify three processes in the video: sedimentation, uplift, and erosion.",
        duration: "9 min",
        planned: true,
        source: "paleomagina",
        ambitoLink: "ambitos.html",
      },
      {
        id: "pm-neanderthal",
        theme: "human",
        playlists: ["during"],
        scope: "A4",
        level: "general",
        icon: "🔥",
        title: "Neanderthals in the territory",
        summary: "Paleomagina series · life, cold, and human evidence.",
        learn: ["Contextualises the Neanderthal world scope.", "Links stone technology and cold adaptation."],
        glossary: ["Homo neanderthalensis", "Paleolithic", "Lithic industry"],
        transcript: "Presents how Neanderthals lived in cold environments, what tools they made, and what remains are documented in the territory. Complements the ante-room and scope A4.",
        teacher: "List three cold-climate adaptations mentioned in the video.",
        duration: "10 min",
        planned: true,
        source: "paleomagina",
        ambitoLink: "ambitos.html",
      },
      {
        id: "pm-excavacion",
        theme: "arch",
        playlists: ["after"],
        scope: "A8",
        level: "school",
        icon: "🔬",
        title: "The science behind an excavation",
        summary: "Paleomagina series · method, recording, and laboratory.",
        learn: ["Shows how archaeological knowledge is produced.", "Links to science and citizenship."],
        glossary: ["Archaeological excavation", "Carbon-14", "Scientific method"],
        transcript: "Describes excavation phases: survey, grid, recording, laboratory, and publication. Humanises the scientific work shown in scope A8.",
        teacher: "Order the video's phases and explain why context matters so much.",
        duration: "11 min",
        planned: true,
        source: "paleomagina",
        ambitoLink: "ambitos.html",
      },
      {
        id: "pm-terraza",
        theme: "museum",
        playlists: ["after"],
        scope: "ATZ",
        level: "general",
        icon: "🌄",
        title: "The final terrace: reading the landscape",
        summary: "Paleomagina series · closing between gallery and real horizon.",
        learn: ["Closes the route linking indoors and landscape.", "Invites visitors to continue beyond the building."],
        glossary: ["Final terrace", "Sierra Mágina", "Heritage interpretation"],
        transcript: "Links what you saw in cases and panels with slopes, ridges, and valleys visible from the terrace. The audiovisual closing of the museographic narrative.",
        teacher: "From the terrace, point out three landscape elements mentioned in the video.",
        duration: "7 min",
        planned: true,
        source: "paleomagina",
        ambitoLink: "ambitos.html",
      },
    ],
  },
};

function getAudiovisualCatalog(lang) {
  return audiovisualCatalog[lang === "en" ? "en" : "es"] || audiovisualCatalog.es;
}

function getAudiovisuals(lang) {
  return getAudiovisualCatalog(lang).items || [];
}
